clear;clc;close all;
addpath(genpath('src/'));
addpath(genpath('data/'));
load("./data/arrayGeometry/array_layout.mat");
pos.src = roomArray.s;
pos.pos_center =[2.6, 2.0, 1.6];
pos.mics_pos = roomArray.BZ_ctrl;
virtual_src_idx = 13;
pos.virtual_src_idx = virtual_src_idx;
freq_params = configure_freq_parameters();
ATF_desired_plane = plane_wave_generator(pos, freq_params);
save('./data/ATF_desired_plane.mat',"ATF_desired_plane");