function results = analyze_all_algorithms_frequency_bands()
%ANALYZE_ALL_ALGORITHMS_FREQUENCY_BANDS Complete bandwise comparison.
%   Uses the completed filters and evaluation matrices only; no algorithm is
%   redesigned. All three parameter settings and all ten algorithms are kept.
%   Frequency bands are non-overlapping on the 50-Hz evaluation grid:
%     Band I   : 100--500 Hz
%     Band II  : 550--1600 Hz
%     Band III : 1650--4000 Hz
%   The 1.63-kHz marker is a geometry-based plane-wave reproduction
%   reference, not a universal algorithm-specific aliasing frequency.

    response_dir = fileparts(mfilename('fullpath'));
    stores = struct();
    stores.nu005 = local_load_run(fullfile(response_dir, ...
        'all_algorithms_fair_results', 'run_20260826_175353'));
    stores.rho1 = local_load_run(fullfile(response_dir, ...
        'racc_pm_parameter_comparison_results', ...
        'rho1_nu0p005_run_20260827_002614'));
    stores.nu01 = local_load_run(fullfile(response_dir, ...
        'racc_pm_parameter_comparison_results', ...
        'rho10_nu0p01_all_run_20260827_002614'));

    algorithms = {'ACC', 'ACC_Reg', 'PM', 'ACC_PM', 'wcRACC', ...
        'NoCT_WCRACC', 'Full_WCRACC', 'POTDC_RACC', 'RPM', ...
        'RACC_PM_Subpro'};
    display_names = {'ACC', 'ACC-Reg', 'PM', 'ACC-PM', 'WCRACC', ...
        'NoCT-WCRACC', 'Full-WCRACC', 'POTDC-RACC', 'RPM', 'RACC-PM'};
    setups = struct( ...
        'id', {'rho10_nu0p005', 'rho1_nu0p005', 'rho10_nu0p01'}, ...
        'label', {'rho=10, nu=0.005', 'rho=1, nu=0.005', ...
                  'rho=10, nu=0.01'});
    bands = struct( ...
        'id', {'band1', 'band2', 'band3'}, ...
        'label', {'Band I: 100-500 Hz', 'Band II: 550-1600 Hz', ...
                  'Band III: 1650-4000 Hz'}, ...
        'lower_hz', {100, 550, 1650}, ...
        'upper_hz', {500, 1600, 4000});

    temperatures = stores.nu005.loaded.para.temperature_vector_celsius(:);
    frequencies = stores.nu005.loaded.freq_params.target_freqs(:).';
    local_assert_common_grid(stores, temperatures, frequencies);
    nominal_mask = abs(temperatures - 22.5) < 1e-10;
    near_mask = temperatures >= 22.2 - 1e-10 & ...
        temperatures <= 22.8 + 1e-10;
    if nnz(nominal_mask) ~= 1 || nnz(near_mask) ~= 7
        error('FrequencyBandAnalysis:TemperatureSelection', ...
            'Expected one nominal and seven near-nominal temperatures.');
    end

    [curves, summary] = local_build_tables(stores, setups, bands, ...
        algorithms, display_names, temperatures, frequencies, ...
        nominal_mask, near_mask);
    winners = local_winner_table(summary, setups, bands);
    recombination_audit = local_recombination_audit(summary, response_dir, ...
        setups, algorithms);

    output_dir = fullfile(response_dir, ...
        'racc_pm_parameter_comparison_results', ...
        'all_algorithms_frequency_band_analysis');
    if ~exist(output_dir, 'dir'), mkdir(output_dir); end
    writetable(curves, fullfile(output_dir, ...
        'all_algorithms_frequency_band_temperature_curves.csv'));
    writetable(summary, fullfile(output_dir, ...
        'all_algorithms_frequency_band_summary.csv'));
    writetable(winners, fullfile(output_dir, ...
        'all_algorithms_frequency_band_winners.csv'));
    writetable(recombination_audit, fullfile(output_dir, ...
        'frequency_band_recombination_audit.csv'));

    preferred_setup = 'rho10_nu0p01';
    near_paths = local_plot_scope(summary, preferred_setup, bands, ...
        algorithms, display_names, 'NearMean', ...
        'Near-nominal mean (22.2-22.8 C)', output_dir);
    sweep_paths = local_plot_scope(summary, preferred_setup, bands, ...
        algorithms, display_names, 'SweepMean', ...
        'Full-sweep mean (20-25 C)', output_dir);
    worst_paths = local_plot_scope(summary, preferred_setup, bands, ...
        algorithms, display_names, 'SweepWorst', ...
        'Full-sweep worst (20-25 C)', output_dir);

    results = struct('setups', setups, 'bands', bands, ...
        'algorithms', {algorithms}, 'display_names', {display_names}, ...
        'curves', curves, 'summary', summary, 'winners', winners, ...
        'recombination_audit', recombination_audit, ...
        'preferred_setup', preferred_setup, ...
        'near_figure_paths', {near_paths}, ...
        'sweep_figure_paths', {sweep_paths}, ...
        'worst_figure_paths', {worst_paths}, 'output_dir', output_dir);
    save(fullfile(output_dir, ...
        'all_algorithms_frequency_band_analysis.mat'), 'results', '-v7.3');
    fprintf('Saved %d summary rows and %d curve rows to:\n%s\n', ...
        height(summary), height(curves), output_dir);
end

function audit = local_recombination_audit(summary, response_dir, ...
        setups, algorithms)
    broadband_file = fullfile(response_dir, ...
        'racc_pm_parameter_comparison_results', ...
        'all_algorithms_combined_analysis', ...
        'all_algorithms_all_settings_summary.csv');
    broadband = readtable(broadband_file, 'TextType', 'string');
    variables = {'NominalACdB', 'NearMeanACdB', 'SweepMeanACdB', ...
        'NominalNSREdB', 'NearMeanNSREdB', 'SweepMeanNSREdB', ...
        'NominalPlanarityPercent', 'NearMeanPlanarityPercent', ...
        'SweepMeanPlanarityPercent', 'NominalAEdB', 'NearMeanAEdB', ...
        'SweepMeanAEdB'};
    rows = numel(setups) * numel(algorithms);
    Setup = strings(rows, 1);
    Algorithm = strings(rows, 1);
    MaxAbsRecombinationDelta = nan(rows, 1);
    row = 0;
    for s = 1:numel(setups)
        for a = 1:numel(algorithms)
            row = row + 1;
            selected = summary.Setup == string(setups(s).id) & ...
                summary.Algorithm == string(algorithms{a});
            source = summary(selected, :);
            reference = broadband(broadband.Setup == string(setups(s).id) & ...
                broadband.Algorithm == string(algorithms{a}), :);
            if height(source) ~= 3 || height(reference) ~= 1
                error('FrequencyBandAnalysis:AuditSelection', ...
                    'Unexpected row count for %s/%s.', ...
                    setups(s).id, algorithms{a});
            end
            weights = source.FrequencyBinCount / sum(source.FrequencyBinCount);
            deltas = nan(numel(variables), 1);
            for v = 1:numel(variables)
                recombined = sum(weights .* source.(variables{v}));
                deltas(v) = abs(recombined - reference.(variables{v}));
            end
            Setup(row) = string(setups(s).id);
            Algorithm(row) = string(algorithms{a});
            MaxAbsRecombinationDelta(row) = max(deltas);
        end
    end
    Passed = MaxAbsRecombinationDelta < 1e-10;
    if ~all(Passed)
        error('FrequencyBandAnalysis:AuditFailed', ...
            'Band recombination failed with maximum delta %.3g.', ...
            max(MaxAbsRecombinationDelta));
    end
    audit = table(Setup, Algorithm, MaxAbsRecombinationDelta, Passed);
end

function store = local_load_run(run_dir)
    if ~isfile(fullfile(run_dir, 'RUN_COMPLETE.txt'))
        error('FrequencyBandAnalysis:IncompleteRun', ...
            'RUN_COMPLETE.txt is missing from %s.', run_dir);
    end
    mats = dir(fullfile(run_dir, 'performance_matrices_*.mat'));
    if numel(mats) ~= 1
        error('FrequencyBandAnalysis:ResultCount', ...
            'Expected one performance MAT in %s; found %d.', ...
            run_dir, numel(mats));
    end
    store = struct();
    store.run_dir = run_dir;
    store.loaded = load(fullfile(mats(1).folder, mats(1).name), ...
        'val_results', 'para', 'freq_params');
    monitor_file = fullfile(run_dir, 'analysis', ...
        'monitor_nsre_postprocess.mat');
    if ~isfile(monitor_file)
        error('FrequencyBandAnalysis:MissingMonitorNSRE', ...
            'Monitor-point NSRE is missing from %s.', run_dir);
    end
    monitor = load(monitor_file, 'results');
    store.monitor = monitor.results;
end

function local_assert_common_grid(stores, temperatures, frequencies)
    names = fieldnames(stores);
    for k = 1:numel(names)
        store = stores.(names{k});
        if ~isequaln(temperatures, ...
                store.loaded.para.temperature_vector_celsius(:)) || ...
                ~isequaln(frequencies, ...
                store.loaded.freq_params.target_freqs(:).')
            error('FrequencyBandAnalysis:GridMismatch', ...
                'All source runs must share temperature/frequency grids.');
        end
    end
end

function [store, source] = local_source_for(stores, setup_id, algorithm)
    switch setup_id
        case 'rho10_nu0p005'
            if strcmp(algorithm, 'ACC')
                store = stores.rho1;
                source = "rho1_nu0p005 (rho-invariant ACC)";
            else
                store = stores.nu005;
                source = "rho10_nu0p005";
            end
        case 'rho1_nu0p005'
            if strcmp(algorithm, 'ACC') || strcmp(algorithm, 'RACC_PM_Subpro')
                store = stores.rho1;
                source = "rho1_nu0p005";
            else
                store = stores.nu005;
                source = "rho10_nu0p005 (rho-invariant algorithm)";
            end
        case 'rho10_nu0p01'
            store = stores.nu01;
            source = "rho10_nu0p01";
        otherwise
            error('FrequencyBandAnalysis:UnknownSetup', ...
                'Unknown setup: %s.', setup_id);
    end
    if ~isfield(store.loaded.val_results, algorithm) || ...
            ~isfield(store.monitor.aligned_monitor_nsre_db, algorithm)
        error('FrequencyBandAnalysis:MissingAlgorithm', ...
            '%s is missing from source %s.', algorithm, source);
    end
end

function [curves, summary] = local_build_tables(stores, setups, bands, ...
        algorithms, display_names, temperatures, frequencies, ...
        nominal_mask, near_mask)
    curve_rows = numel(setups) * numel(bands) * numel(algorithms) * ...
        numel(temperatures);
    summary_rows = numel(setups) * numel(bands) * numel(algorithms);
    curve_cells = cell(curve_rows, 15);
    summary_cells = cell(summary_rows, 30);
    curve_row = 0;
    summary_row = 0;

    for s = 1:numel(setups)
        for b = 1:numel(bands)
            band_mask = frequencies >= bands(b).lower_hz & ...
                frequencies <= bands(b).upper_hz;
            band_frequencies = frequencies(band_mask);
            if isempty(band_frequencies)
                error('FrequencyBandAnalysis:EmptyBand', ...
                    'No frequency bins found for %s.', bands(b).label);
            end
            for a = 1:numel(algorithms)
                [store, source] = local_source_for(stores, setups(s).id, ...
                    algorithms{a});
                performance = store.loaded.val_results.(algorithms{a});
                aligned_nsre = store.monitor.aligned_monitor_nsre_db. ...
                    (algorithms{a});
                data = struct( ...
                    'AC', mean(performance.AC(:, band_mask), 2, 'omitnan'), ...
                    'NSRE', mean(aligned_nsre(:, band_mask), 2, 'omitnan'), ...
                    'Planarity', mean(performance.Planarity(:, band_mask), ...
                        2, 'omitnan'), ...
                    'AE', mean(performance.AE(:, band_mask), 2, 'omitnan'));

                for t = 1:numel(temperatures)
                    curve_row = curve_row + 1;
                    curve_cells(curve_row, :) = {setups(s).id, setups(s).label, ...
                        bands(b).id, bands(b).label, band_frequencies(1), ...
                        band_frequencies(end), numel(band_frequencies), ...
                        algorithms{a}, display_names{a}, char(source), ...
                        temperatures(t), data.AC(t), data.NSRE(t), ...
                        data.Planarity(t), data.AE(t)};
                end

                summary_row = summary_row + 1;
                summary_cells(summary_row, :) = {setups(s).id, ...
                    setups(s).label, bands(b).id, bands(b).label, ...
                    band_frequencies(1), band_frequencies(end), ...
                    numel(band_frequencies), algorithms{a}, ...
                    display_names{a}, char(source), ...
                    data.AC(nominal_mask), mean(data.AC(near_mask)), ...
                    min(data.AC(near_mask)), mean(data.AC), min(data.AC), ...
                    data.NSRE(nominal_mask), mean(data.NSRE(near_mask)), ...
                    max(data.NSRE(near_mask)), mean(data.NSRE), ...
                    max(data.NSRE), data.Planarity(nominal_mask), ...
                    mean(data.Planarity(near_mask)), ...
                    min(data.Planarity(near_mask)), mean(data.Planarity), ...
                    min(data.Planarity), data.AE(nominal_mask), ...
                    mean(data.AE(near_mask)), max(data.AE(near_mask)), ...
                    mean(data.AE), max(data.AE)};
            end
        end
    end

    curve_names = {'Setup', 'SetupLabel', 'Band', 'BandLabel', ...
        'BandFirstFrequencyHz', 'BandLastFrequencyHz', 'FrequencyBinCount', ...
        'Algorithm', 'AlgorithmLabel', 'SourceRun', 'TemperatureC', ...
        'ACdB', 'AlignedMonitorNSREdB', 'PlanarityPercent', 'AEdB'};
    summary_names = {'Setup', 'SetupLabel', 'Band', 'BandLabel', ...
        'BandFirstFrequencyHz', 'BandLastFrequencyHz', 'FrequencyBinCount', ...
        'Algorithm', 'AlgorithmLabel', 'SourceRun', ...
        'NominalACdB', 'NearMeanACdB', 'NearWorstACdB', ...
        'SweepMeanACdB', 'SweepWorstACdB', ...
        'NominalNSREdB', 'NearMeanNSREdB', 'NearWorstNSREdB', ...
        'SweepMeanNSREdB', 'SweepWorstNSREdB', ...
        'NominalPlanarityPercent', 'NearMeanPlanarityPercent', ...
        'NearWorstPlanarityPercent', 'SweepMeanPlanarityPercent', ...
        'SweepWorstPlanarityPercent', 'NominalAEdB', 'NearMeanAEdB', ...
        'NearWorstAEdB', 'SweepMeanAEdB', 'SweepWorstAEdB'};
    curves = cell2table(curve_cells, 'VariableNames', curve_names);
    summary = cell2table(summary_cells, 'VariableNames', summary_names);
    curve_string_names = {'Setup', 'SetupLabel', 'Band', 'BandLabel', ...
        'Algorithm', 'AlgorithmLabel', 'SourceRun'};
    summary_string_names = curve_string_names;
    for k = 1:numel(curve_string_names)
        curves.(curve_string_names{k}) = ...
            string(curves.(curve_string_names{k}));
        summary.(summary_string_names{k}) = ...
            string(summary.(summary_string_names{k}));
    end
end

function winners = local_winner_table(summary, setups, bands)
    scopes = {'NearMean', 'SweepMean', 'SweepWorst'};
    metrics = {'ACdB', 'NSREdB', 'PlanarityPercent', 'AEdB'};
    directions = [1, -1, 1, -1];
    rows = numel(setups) * numel(bands) * numel(scopes) * numel(metrics);
    cells = cell(rows, 10);
    row = 0;
    for s = 1:numel(setups)
        for b = 1:numel(bands)
            subset = summary(summary.Setup == string(setups(s).id) & ...
                summary.Band == string(bands(b).id), :);
            for q = 1:numel(scopes)
                for m = 1:numel(metrics)
                    row = row + 1;
                    variable = [scopes{q} metrics{m}];
                    values = subset.(variable);
                    ordered = sort(values, 'descend');
                    if directions(m) < 0, ordered = sort(values, 'ascend'); end
                    winner_index = find(values == ordered(1), 1, 'first');
                    runner_index = find(values == ordered(2), 1, 'first');
                    cells(row, :) = {setups(s).id, setups(s).label, ...
                        bands(b).id, bands(b).label, scopes{q}, metrics{m}, ...
                        char(subset.AlgorithmLabel(winner_index)), ...
                        values(winner_index), ...
                        char(subset.AlgorithmLabel(runner_index)), ...
                        abs(values(winner_index) - values(runner_index))};
                end
            end
        end
    end
    winners = cell2table(cells, 'VariableNames', {'Setup', 'SetupLabel', ...
        'Band', 'BandLabel', 'Scope', 'Metric', 'Winner', 'WinnerValue', ...
        'RunnerUp', 'AbsoluteMargin'});
end

function paths = local_plot_scope(summary, setup_id, bands, algorithms, ...
        display_names, prefix, heading, output_dir)
    specifications = { ...
        [prefix 'ACdB'], 'AC (dB)'; ...
        [prefix 'NSREdB'], 'Aligned NSRE (dB)'; ...
        [prefix 'PlanarityPercent'], 'Planarity (%)'; ...
        [prefix 'AEdB'], 'Array effort (dB)'};
    base = fullfile(output_dir, [setup_id '_' lower(prefix) ...
        '_frequency_band_comparison']);
    fig = figure('Color', 'w', 'ToolBar', 'none', ...
        'Position', [100, 100, 1500, 820]);
    layout = tiledlayout(fig, 2, 2, 'TileSpacing', 'compact', ...
        'Padding', 'compact');
    title(layout, heading, 'FontName', 'Times New Roman', 'FontSize', 13);
    colors = [0.0000, 0.4470, 0.7410; 0.8500, 0.3250, 0.0980; ...
        0.9290, 0.6940, 0.1250];
    for m = 1:size(specifications, 1)
        values = nan(numel(algorithms), numel(bands));
        for a = 1:numel(algorithms)
            for b = 1:numel(bands)
                selected = summary.Setup == string(setup_id) & ...
                    summary.Algorithm == string(algorithms{a}) & ...
                    summary.Band == string(bands(b).id);
                if nnz(selected) ~= 1
                    error('FrequencyBandAnalysis:PlotSelection', ...
                        'Expected one row for %s/%s/%s.', ...
                        setup_id, algorithms{a}, bands(b).id);
                end
                values(a, b) = summary.(specifications{m, 1})(selected);
            end
        end
        ax = nexttile(layout);
        disableDefaultInteractivity(ax);
        ax.Toolbar.Visible = 'off';
        bars = bar(ax, values, 'grouped');
        for b = 1:numel(bars), bars(b).FaceColor = colors(b, :); end
        grid(ax, 'on'); box(ax, 'on');
        ax.XTick = 1:numel(algorithms);
        ax.XTickLabel = display_names;
        ax.XTickLabelRotation = 28;
        ylabel(ax, specifications{m, 2});
        set(ax, 'FontName', 'Times New Roman', 'FontSize', 9);
        if m == 1
            legend(ax, {bands.label}, 'Location', 'best', ...
                'NumColumns', numel(bands));
        end
    end
    paths = {[base '.png'], [base '.pdf'], [base '.fig']};
    exportgraphics(fig, paths{1}, 'Resolution', 300);
    exportgraphics(fig, paths{2}, 'ContentType', 'vector');
    savefig(fig, paths{3});
    close(fig);
end
