function results = run_racc_pm_rho_tradeoff_sweep(user_config)
%RUN_RACC_PM_RHO_TRADEOFF_SWEEP Reviewer-facing RACC-PM rho diagnostic.
%   Filters are designed from the nominal 22.5-C control ATFs using the
%   final common nu=0.01 uncertainty radii and the final control-derived
%   alpha(f). Only the maintained no-suffix RACC_PM_Sub implementation is
%   used. Native AC, NSRE, and scale-invariant AE are reported on both the
%   design/control grid and the independent evaluation grid, averaged over
%   22.2--22.8 C. No post-hoc complex gain is applied to RACC-PM.

    if nargin < 1 || isempty(user_config), user_config = struct(); end
    response_dir = fileparts(mfilename('fullpath'));
    project_root = fileparts(response_dir);
    addpath(fullfile(project_root, 'src', 'algorithm'));
    addpath(fullfile(project_root, 'src', 'utils'));
    addpath(fullfile(project_root, 'src', 'evaluations'), '-begin');

    config = local_default_config(response_dir);
    config = local_apply_overrides(config, user_config);
    local_validate_config(config);
    rng(config.random_seed, 'twister');

    expected_solver = fullfile(project_root, 'src', 'algorithm', ...
        'RACC_PM_Sub.m');
    active_solver = which('RACC_PM_Sub');
    if ~strcmpi(active_solver, expected_solver)
        error('RACCPMRhoSweep:SolverResolutionMismatch', ...
            'Expected %s but MATLAB resolves %s.', ...
            expected_solver, active_solver);
    end
    expected_evaluator = fullfile(project_root, 'src', 'evaluations', ...
        'evaluate_performance.m');
    active_evaluator = which('evaluate_performance');
    if ~strcmpi(active_evaluator, expected_evaluator)
        error('RACCPMRhoSweep:EvaluatorResolutionMismatch', ...
            'Expected %s but MATLAB resolves %s.', ...
            expected_evaluator, active_evaluator);
    end
    if exist('cvx_begin', 'file') == 0
        error('RACCPMRhoSweep:CVXMissing', ...
            'CVX with MOSEK is required.');
    end

    output_dir = local_output_directory(config);
    if ~isfolder(output_dir), mkdir(output_dir); end
    checkpoint_dir = output_dir;
    if strlength(string(config.filter_checkpoint_dir)) > 0
        checkpoint_dir = char(config.filter_checkpoint_dir);
    end
    fprintf('RACC-PM rho sweep output: %s\n', output_dir);
    fprintf('Filter checkpoints: %s\n', checkpoint_dir);
    fprintf('Solver: %s\nEvaluator resolution: %s\n', ...
        active_solver, active_evaluator);

    %% Load the final parameter protocol and nominal design data.
    final_result = load(config.final_parameter_result, 'freq_params', ...
        'uncertainty_config');
    all_frequencies_hz = final_result.freq_params.target_freqs(:).';
    frequency_indices = local_frequency_indices(all_frequencies_hz, ...
        config.frequencies_hz);
    frequencies_hz = all_frequencies_hz(frequency_indices);
    alpha_reference = final_result.freq_params.alpha(frequency_indices);
    alpha = alpha_reference .* 10^(-config.alpha_margin_db / 10);
    alpha_source = 'nominal NoCT-WCRACC control-point AC';
    if isfield(final_result, 'uncertainty_config') && ...
            isfield(final_result.uncertainty_config, 'alpha_source')
        alpha_source = final_result.uncertainty_config.alpha_source;
    end
    epsilon_B = final_result.freq_params.epsilon.B(frequency_indices);
    epsilon_D = final_result.freq_params.epsilon.D(frequency_indices);

    data_dir = fullfile(project_root, 'data', 'SimulateRIR', 'temperature');
    nominal_file = get_data_filename(data_dir, 'temperature', ...
        config.nominal_temperature_c);
    nominal = load(nominal_file, 'ATF_BZ', 'ATF_DZ');
    HB_control_nominal = nominal.ATF_BZ.ctrl(:, :, frequency_indices);
    HD_control_nominal = nominal.ATF_DZ.ctrl(:, :, frequency_indices);
    clear nominal
    desired_saved = load(fullfile(project_root, 'data', ...
        'ATF_desired_plane.mat'), 'ATF_desired_plane');
    desired_control = ...
        desired_saved.ATF_desired_plane(:, frequency_indices);

    geometry = load(fullfile(project_root, 'data', 'arrayGeometry', ...
        'array_layout.mat'), 'roomArray');
    frequency_metadata = load(fullfile(data_dir, 'para.mat'), 'para');
    position = struct('src', geometry.roomArray.s, ...
        'pos_center', [2.6, 2.0, 1.6], ...
        'virtual_src_idx', config.virtual_source_idx, ...
        'mics_pos', geometry.roomArray.BZ_ctrl);
    desired_control_generated = local_plane_wave_generator( ...
        position, frequency_metadata.para.freq_params);
    desired_control_error = max(abs(desired_control_generated(:, ...
        frequency_indices) - desired_control), [], 'all');
    if desired_control_error > 1e-10
        error('RACCPMRhoSweep:DesiredFieldMismatch', ...
            'Generated and saved control targets differ by %.3g.', ...
            desired_control_error);
    end
    position.mics_pos = geometry.roomArray.BZ_eval;
    desired_evaluation_all = local_plane_wave_generator( ...
        position, frequency_metadata.para.freq_params);
    desired_evaluation = desired_evaluation_all(:, frequency_indices);

    fprintf('Frequencies: %s Hz\n', mat2str(frequencies_hz));
    fprintf('rho grid: %s\n', mat2str(config.rho_values));
    fprintf('Alpha reference: %s\n', alpha_source);
    fprintf('Reference alpha: %s\n', mat2str(alpha_reference, 8));
    fprintf('Alpha margin: %.3f dB\n', config.alpha_margin_db);
    fprintf('Design alpha: %s\n', mat2str(alpha, 8));
    fprintf('Fixed epsilon_B: %s\n', mat2str(epsilon_B, 8));
    fprintf('Fixed epsilon_D: %s\n', mat2str(epsilon_D, 8));

    %% Design/checkpoint each frequency independently.
    num_rho = numel(config.rho_values);
    num_frequencies = numel(frequencies_hz);
    loudspeaker_count = size(HB_control_nominal, 2);
    filters = nan(loudspeaker_count, num_frequencies, num_rho);
    statuses = strings(num_frequencies, num_rho);
    solve_seconds = nan(num_frequencies, num_rho);
    nominal_objective_ratio = nan(num_frequencies, num_rho);
    zero_dominated = false(num_frequencies, num_rho);
    for rho_index = 1:num_rho
        rho = config.rho_values(rho_index);
        for frequency_no = 1:num_frequencies
            checkpoint_name = sprintf( ...
                'filter_rho_%s_%gHz.mat', local_number_tag(rho), ...
                frequencies_hz(frequency_no));
            source_checkpoint = fullfile(checkpoint_dir, checkpoint_name);
            if config.resume && isfile(source_checkpoint)
                saved = load(source_checkpoint, 'filter', 'status', ...
                    'elapsed_seconds');
                filters(:, frequency_no, rho_index) = saved.filter;
                statuses(frequency_no, rho_index) = string(saved.status);
                solve_seconds(frequency_no, rho_index) = ...
                    saved.elapsed_seconds;
                nominal_objective_ratio(frequency_no, rho_index) = ...
                    local_nominal_objective_ratio(saved.filter, ...
                    HB_control_nominal(:, :, frequency_no), ...
                    HD_control_nominal(:, :, frequency_no), ...
                    desired_control(:, frequency_no), rho, config.mu, ...
                    alpha(frequency_no));
                zero_dominated(frequency_no, rho_index) = ...
                    nominal_objective_ratio(frequency_no, rho_index) > ...
                    1 + config.zero_dominance_tolerance;
                fprintf('Reused rho=%g, %.2f Hz.\n', rho, ...
                    frequencies_hz(frequency_no));
                continue;
            end

            robust_para = struct();
            robust_para.scale = 1;
            robust_para.epsilon = struct('B', epsilon_B, ...
                'D', epsilon_D);
            robust_para.rho = rho;
            robust_para.mu = config.mu;
            robust_para.alpha = alpha;
            robust_para.racc_pm = struct( ...
                'mosek_threads', config.mosek_threads, ...
                'rank_fraction_threshold', ...
                config.rank_fraction_threshold);
            fprintf('Solving rho=%g, %.2f Hz (%d/%d, %d/%d)...\n', ...
                rho, frequencies_hz(frequency_no), rho_index, num_rho, ...
                frequency_no, num_frequencies);
            timer = tic;
            result = RACC_PM_Sub(HB_control_nominal, ...
                HD_control_nominal, desired_control, robust_para, ...
                frequency_no);
            elapsed_seconds = toc(timer);
            filter = result.w(:, frequency_no);
            status = result.status(frequency_no);
            if ~(status == "Solved" || status == "Inaccurate/Solved") || ...
                    any(~isfinite(filter)) || norm(filter) == 0
                error('RACCPMRhoSweep:DesignFailed', ...
                    'rho=%g, %.2f Hz failed with status %s.', ...
                    rho, frequencies_hz(frequency_no), status);
            end
            filters(:, frequency_no, rho_index) = filter;
            statuses(frequency_no, rho_index) = status;
            solve_seconds(frequency_no, rho_index) = elapsed_seconds;
            nominal_objective_ratio(frequency_no, rho_index) = ...
                local_nominal_objective_ratio(filter, ...
                HB_control_nominal(:, :, frequency_no), ...
                HD_control_nominal(:, :, frequency_no), ...
                desired_control(:, frequency_no), rho, config.mu, ...
                alpha(frequency_no));
            zero_dominated(frequency_no, rho_index) = ...
                nominal_objective_ratio(frequency_no, rho_index) > ...
                1 + config.zero_dominance_tolerance;
            if zero_dominated(frequency_no, rho_index)
                warning('RACCPMRhoSweep:ZeroDominatedRecovery', ...
                    ['Recovered filter at rho=%g and %.2f Hz has nominal ' ...
                    'objective ratio %.6g > zero-filter baseline.'], ...
                    rho, frequencies_hz(frequency_no), ...
                    nominal_objective_ratio(frequency_no, rho_index));
            end
            output_checkpoint = fullfile(output_dir, checkpoint_name);
            frequency_hz = frequencies_hz(frequency_no);
            alpha_reference_value = alpha_reference(frequency_no);
            alpha_value = alpha(frequency_no);
            alpha_margin_db = config.alpha_margin_db;
            epsilon_B_value = epsilon_B(frequency_no);
            epsilon_D_value = epsilon_D(frequency_no);
            recovery_nominal_objective_ratio = ...
                nominal_objective_ratio(frequency_no, rho_index);
            recovery_zero_dominated = ...
                zero_dominated(frequency_no, rho_index);
            save(output_checkpoint, 'filter', 'status', 'elapsed_seconds', ...
                'rho', 'frequency_no', 'frequency_hz', ...
                'alpha_source', 'alpha_reference_value', 'alpha_value', ...
                'alpha_margin_db', 'epsilon_B_value', 'epsilon_D_value', ...
                'recovery_nominal_objective_ratio', ...
                'recovery_zero_dominated', '-v7.3');
            fprintf('Completed in %.2f s with status %s.\n', ...
                elapsed_seconds, status);
        end
    end

    %% Evaluate frozen filters on the independent temperature/evaluation grid.
    num_temperatures = numel(config.test_temperatures_c);
    rows = num_rho * num_frequencies * num_temperatures;
    Rho = nan(rows, 1);
    FrequencyHz = nan(rows, 1);
    TemperatureC = nan(rows, 1);
    ControlACdB = nan(rows, 1);
    EvaluationACdB = nan(rows, 1);
    ControlNSREdB = nan(rows, 1);
    EvaluationNSREdB = nan(rows, 1);
    ControlAEdB = nan(rows, 1);
    EvaluationAEdB = nan(rows, 1);
    row = 0;
    for temperature_index = 1:num_temperatures
        temperature_c = config.test_temperatures_c(temperature_index);
        test_file = get_data_filename(data_dir, 'temperature', temperature_c);
        test = load(test_file, 'ATF_BZ', 'ATF_DZ');
        HB_control = test.ATF_BZ.ctrl(:, :, frequency_indices);
        HD_control = test.ATF_DZ.ctrl(:, :, frequency_indices);
        HB_evaluation = test.ATF_BZ.eval(:, :, frequency_indices);
        HD_evaluation = test.ATF_DZ.eval(:, :, frequency_indices);
        clear test
        for rho_index = 1:num_rho
            for frequency_no = 1:num_frequencies
                row = row + 1;
                raw_filter = filters(:, frequency_no, rho_index);
                HBe = HB_evaluation(:, :, frequency_no);
                HDe = HD_evaluation(:, :, frequency_no);
                HBc = HB_control(:, :, frequency_no);
                HDc = HD_control(:, :, frequency_no);
                Rho(row) = config.rho_values(rho_index);
                FrequencyHz(row) = frequencies_hz(frequency_no);
                TemperatureC(row) = temperature_c;
                ControlACdB(row) = local_ac_db(raw_filter, HBc, HDc);
                EvaluationACdB(row) = local_ac_db(raw_filter, HBe, HDe);
                ControlNSREdB(row) = local_nsre_db(raw_filter, HBc, ...
                    desired_control(:, frequency_no));
                EvaluationNSREdB(row) = local_nsre_db(raw_filter, ...
                    HBe, desired_evaluation(:, frequency_no));
                ControlAEdB(row) = local_ae_db(raw_filter, HBc, ...
                    config.virtual_source_idx, config.target_spl_db);
                EvaluationAEdB(row) = local_ae_db(raw_filter, HBe, ...
                    config.virtual_source_idx, config.target_spl_db);
            end
        end
        fprintf('Evaluated %.1f C (%d/%d).\n', temperature_c, ...
            temperature_index, num_temperatures);
    end
    metrics = table(Rho, FrequencyHz, TemperatureC, ControlACdB, ...
        EvaluationACdB, ControlNSREdB, EvaluationNSREdB, ...
        ControlAEdB, EvaluationAEdB);
    writetable(metrics, fullfile(output_dir, ...
        'rho_tradeoff_temperature_metrics.csv'));
    summary = local_summary(metrics, config.rho_values, frequencies_hz, ...
        config.nominal_temperature_c);
    writetable(summary, fullfile(output_dir, ...
        'rho_tradeoff_summary.csv'));
    figure_paths = local_plot(summary, config.rho_values, ...
        frequencies_hz, output_dir);

    results = struct('config', config, 'output_dir', output_dir, ...
        'active_solver', active_solver, ...
        'active_evaluator', active_evaluator, ...
        'frequencies_hz', frequencies_hz, ...
        'frequency_indices', frequency_indices, ...
        'alpha_source', alpha_source, ...
        'alpha_reference', alpha_reference, 'alpha', alpha, ...
        'epsilon_B', epsilon_B, 'epsilon_D', epsilon_D, ...
        'desired_control_regeneration_error', desired_control_error, ...
        'filters', filters, 'statuses', statuses, ...
        'solve_seconds', solve_seconds, ...
        'nominal_objective_ratio', nominal_objective_ratio, ...
        'zero_dominated', zero_dominated, ...
        'metrics', metrics, 'summary', summary, ...
        'figure_paths', figure_paths);
    save(fullfile(output_dir, 'rho_tradeoff_results.mat'), ...
        'results', '-v7.3');
    marker = fopen(fullfile(output_dir, 'RUN_COMPLETE.txt'), 'w');
    if marker >= 0
        fprintf(marker, ['Completed %s\nFinal protocol: nu_B=nu_D=0.01, ' ...
            'mu=1, %s with %.3f-dB margin\nSolver: RACC_PM_Sub ' ...
            '(no suffix); GLS: not used\nNative control/evaluation metrics; ' ...
            'no post-hoc complex gain\n'], char(datetime('now')), ...
            alpha_source, config.alpha_margin_db);
        fclose(marker);
    end
    disp(summary);
    fprintf('Completed RACC-PM rho sweep: %s\n', output_dir);
end

function config = local_default_config(response_dir)
    config = struct();
    config.rho_values = logspace(-3, 3, 15);
    config.frequencies_hz = [500, 1000, 4000];
    config.nominal_temperature_c = 22.5;
    config.test_temperatures_c = 22.2:0.1:22.8;
    config.mu = 1;
    config.alpha_margin_db = 3;
    config.zero_dominance_tolerance = 1e-3;
    config.virtual_source_idx = 13;
    config.target_spl_db = 76;
    config.mosek_threads = 2;
    config.rank_fraction_threshold = 0.98;
    config.random_seed = 20260908;
    config.resume = true;
    config.output_dir = '';
    config.filter_checkpoint_dir = '';
    config.output_root = fullfile(response_dir, ...
        'racc_pm_rho_tradeoff_results');
    config.final_parameter_result = fullfile(response_dir, ...
        'racc_pm_parameter_comparison_results', ...
        'rho10_nu0p01_all_run_20260827_002614', ...
        'performance_matrices_20260827_021428.mat');
end

function config = local_apply_overrides(config, overrides)
    names = fieldnames(overrides);
    for index = 1:numel(names)
        if ~isfield(config, names{index})
            error('RACCPMRhoSweep:UnknownConfigField', ...
                'Unknown configuration field: %s.', names{index});
        end
        config.(names{index}) = overrides.(names{index});
    end
end

function local_validate_config(config)
    validateattributes(config.rho_values, {'numeric'}, ...
        {'vector', 'real', 'finite', 'positive', 'nonempty'});
    validateattributes(config.frequencies_hz, {'numeric'}, ...
        {'vector', 'real', 'finite', 'positive', 'nonempty'});
    validateattributes(config.test_temperatures_c, {'numeric'}, ...
        {'vector', 'real', 'finite', 'nonempty'});
    validateattributes(config.mu, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'nonnegative'});
    validateattributes(config.alpha_margin_db, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'nonnegative'});
    validateattributes(config.zero_dominance_tolerance, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'nonnegative'});
    validateattributes(config.rank_fraction_threshold, {'numeric'}, ...
        {'scalar', 'real', 'finite', '>', 0, '<=', 1});
    if ~isfile(config.final_parameter_result)
        error('RACCPMRhoSweep:MissingFinalResult', ...
            'Missing final parameter result: %s', ...
            config.final_parameter_result);
    end
    if strlength(string(config.filter_checkpoint_dir)) > 0 && ...
            ~isfolder(config.filter_checkpoint_dir)
        error('RACCPMRhoSweep:MissingCheckpointDirectory', ...
            'Missing filter checkpoint directory: %s', ...
            config.filter_checkpoint_dir);
    end
end

function output_dir = local_output_directory(config)
    if strlength(string(config.output_dir)) > 0
        output_dir = char(config.output_dir);
    else
        timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
        output_dir = fullfile(config.output_root, ['run_' timestamp]);
    end
end

function indices = local_frequency_indices(all_frequencies, requested)
    indices = zeros(size(requested));
    for index = 1:numel(requested)
        [difference, indices(index)] = min(abs( ...
            all_frequencies - requested(index)));
        if difference > 1e-9
            error('RACCPMRhoSweep:FrequencyUnavailable', ...
                'Requested frequency %.6g Hz is unavailable.', ...
                requested(index));
        end
    end
end

function value = local_ac_db(w, HB, HD)
    ratio = size(HD, 1) * norm(HB * w)^2 / max( ...
        size(HB, 1) * norm(HD * w)^2, realmin);
    value = 10 * log10(max(real(ratio), realmin));
end

function value = local_nsre_db(w, HB, desired)
    value = 10 * log10(max(norm(HB * w - desired)^2 / ...
        max(norm(desired)^2, realmin), realmin));
end

function value = local_nominal_objective_ratio(w, HB, HD, desired, ...
        rho, mu, alpha)
    bright_energy = norm(HB * w)^2;
    dark_energy = norm(HD * w)^2;
    reproduction_error = norm(HB * w - desired)^2;
    objective = reproduction_error + mu * dark_energy + ...
        rho * (alpha * dark_energy - bright_energy);
    value = real(objective) / max(norm(desired)^2, realmin);
end

function value = local_ae_db(w, HB, virtual_source_index, target_spl_db)
    reference = zeros(size(w));
    reference(virtual_source_index) = 1;
    target_pressure = 20e-6 * 10^(target_spl_db / 20);
    current_rms = sqrt(mean(abs(HB * w).^2));
    calibrated_w = w * target_pressure / max(current_rms, realmin);
    RB = HB' * HB;
    energy_ratio = real(reference' * RB * reference) / max( ...
        real(calibrated_w' * RB * calibrated_w), realmin);
    effort_ratio = real(calibrated_w' * calibrated_w);
    value = 10 * log10(max(effort_ratio * energy_ratio, realmin));
end

function desired = local_plane_wave_generator(position, freq_params)
    source_position = position.src(position.virtual_src_idx, :);
    direction = position.pos_center - source_position;
    direction = direction / norm(direction);
    wave_numbers = 2 * pi * freq_params.target_freqs(:) / 343;
    phase_delay = position.mics_pos * (wave_numbers .* direction).';
    desired = exp(-1i * phase_delay);
end

function summary = local_summary(metrics, rho_values, frequencies, nominal_c)
    rows = numel(rho_values) * numel(frequencies);
    Rho = nan(rows, 1);
    FrequencyHz = nan(rows, 1);
    NominalControlACdB = nan(rows, 1);
    NominalEvaluationACdB = nan(rows, 1);
    MeanControlACdB = nan(rows, 1);
    MeanEvaluationACdB = nan(rows, 1);
    MinimumControlACdB = nan(rows, 1);
    MinimumEvaluationACdB = nan(rows, 1);
    NominalControlNSREdB = nan(rows, 1);
    NominalEvaluationNSREdB = nan(rows, 1);
    MeanControlNSREdB = nan(rows, 1);
    MeanEvaluationNSREdB = nan(rows, 1);
    MaximumControlNSREdB = nan(rows, 1);
    MaximumEvaluationNSREdB = nan(rows, 1);
    NominalControlAEdB = nan(rows, 1);
    NominalEvaluationAEdB = nan(rows, 1);
    MeanControlAEdB = nan(rows, 1);
    MeanEvaluationAEdB = nan(rows, 1);
    MaximumControlAEdB = nan(rows, 1);
    MaximumEvaluationAEdB = nan(rows, 1);
    MeanACGridDifference_dB = nan(rows, 1);
    MeanNSREGridDifference_dB = nan(rows, 1);
    MeanAEGridDifference_dB = nan(rows, 1);
    row = 0;
    for rho_index = 1:numel(rho_values)
        for frequency_no = 1:numel(frequencies)
            row = row + 1;
            mask = abs(metrics.Rho - rho_values(rho_index)) < ...
                max(eps(rho_values(rho_index)) * 8, realmin) & ...
                metrics.FrequencyHz == frequencies(frequency_no);
            values = metrics(mask, :);
            nominal = values(abs(values.TemperatureC - nominal_c) < ...
                1e-9, :);
            Rho(row) = rho_values(rho_index);
            FrequencyHz(row) = frequencies(frequency_no);
            NominalControlACdB(row) = nominal.ControlACdB;
            NominalEvaluationACdB(row) = nominal.EvaluationACdB;
            MeanControlACdB(row) = mean(values.ControlACdB);
            MeanEvaluationACdB(row) = mean(values.EvaluationACdB);
            MinimumControlACdB(row) = min(values.ControlACdB);
            MinimumEvaluationACdB(row) = min(values.EvaluationACdB);
            NominalControlNSREdB(row) = nominal.ControlNSREdB;
            NominalEvaluationNSREdB(row) = nominal.EvaluationNSREdB;
            MeanControlNSREdB(row) = mean(values.ControlNSREdB);
            MeanEvaluationNSREdB(row) = mean(values.EvaluationNSREdB);
            MaximumControlNSREdB(row) = max(values.ControlNSREdB);
            MaximumEvaluationNSREdB(row) = ...
                max(values.EvaluationNSREdB);
            NominalControlAEdB(row) = nominal.ControlAEdB;
            NominalEvaluationAEdB(row) = nominal.EvaluationAEdB;
            MeanControlAEdB(row) = mean(values.ControlAEdB);
            MeanEvaluationAEdB(row) = mean(values.EvaluationAEdB);
            MaximumControlAEdB(row) = max(values.ControlAEdB);
            MaximumEvaluationAEdB(row) = max(values.EvaluationAEdB);
            MeanACGridDifference_dB(row) = ...
                MeanEvaluationACdB(row) - MeanControlACdB(row);
            MeanNSREGridDifference_dB(row) = ...
                MeanEvaluationNSREdB(row) - MeanControlNSREdB(row);
            MeanAEGridDifference_dB(row) = ...
                MeanEvaluationAEdB(row) - MeanControlAEdB(row);
        end
    end
    summary = table(Rho, FrequencyHz, NominalControlACdB, ...
        NominalEvaluationACdB, MeanControlACdB, MeanEvaluationACdB, ...
        MinimumControlACdB, MinimumEvaluationACdB, ...
        NominalControlNSREdB, NominalEvaluationNSREdB, ...
        MeanControlNSREdB, MeanEvaluationNSREdB, ...
        MaximumControlNSREdB, MaximumEvaluationNSREdB, ...
        NominalControlAEdB, NominalEvaluationAEdB, ...
        MeanControlAEdB, MeanEvaluationAEdB, ...
        MaximumControlAEdB, MaximumEvaluationAEdB, ...
        MeanACGridDifference_dB, MeanNSREGridDifference_dB, ...
        MeanAEGridDifference_dB);
end

function paths = local_plot(summary, rho_values, frequencies, output_dir)
    evaluation_mean_fields = {'MeanEvaluationACdB', ...
        'MeanEvaluationNSREdB', 'MeanEvaluationAEdB'};
    control_mean_fields = {'MeanControlACdB', 'MeanControlNSREdB', ...
        'MeanControlAEdB'};
    evaluation_nominal_fields = {'NominalEvaluationACdB', ...
        'NominalEvaluationNSREdB', 'NominalEvaluationAEdB'};
    control_nominal_fields = {'NominalControlACdB', ...
        'NominalControlNSREdB', 'NominalControlAEdB'};
    paths = struct();
    paths.evaluation = local_plot_one_grid(summary, rho_values, ...
        frequencies, output_dir, evaluation_mean_fields, ...
        'rho_tradeoff_evaluation_points_ac_nsre_ae');
    paths.control = local_plot_one_grid(summary, rho_values, frequencies, ...
        output_dir, control_mean_fields, ...
        'rho_tradeoff_control_points_ac_nsre_ae');
    paths.nominal_evaluation = local_plot_one_grid(summary, rho_values, ...
        frequencies, output_dir, evaluation_nominal_fields, ...
        'rho_tradeoff_nominal_evaluation_points_ac_nsre_ae');
    paths.nominal_control = local_plot_one_grid(summary, rho_values, ...
        frequencies, output_dir, control_nominal_fields, ...
        'rho_tradeoff_nominal_control_points_ac_nsre_ae');
end

function paths = local_plot_one_grid(summary, rho_values, frequencies, ...
        output_dir, fields, basename)
    % Reuse the visual language of the manuscript's earlier rho figures:
    % saturated blue/red/gold curves, open markers, strong axes, and quiet
    % grey major/minor grids. Distinct markers also remain legible in print.
    palette = [0.0000, 0.4470, 0.7410; ...
               0.8000, 0.2400, 0.2000; ...
               0.9290, 0.6940, 0.1250];
    colors = palette(1:numel(frequencies), :);
    markers = {'o', 's', 'd'};
    figure_handle = figure('Color', 'w', ...
        'Position', [100, 100, 1240, 405], ...
        'ToolBar', 'figure', 'MenuBar', 'figure');
    layout = tiledlayout(1, 3, 'TileSpacing', 'compact', ...
        'Padding', 'loose');
    labels = {'AC: [dB]', 'NSRE: [dB]', 'AE: [dB]'};
    titles = {'(a) Acoustic contrast', ...
        '(b) Normalized reproduction error', ...
        '(c) Array effort'};
    handles = gobjects(numel(frequencies), 1);
    for metric_no = 1:3
        metric_value_cells = cell(numel(frequencies), 1);
        axis_handle = nexttile(layout, metric_no);
        hold(axis_handle, 'on'); grid(axis_handle, 'on');
        box(axis_handle, 'on');
        disableDefaultInteractivity(axis_handle);
        if ~isempty(axis_handle.Toolbar)
            axis_handle.Toolbar.Visible = 'off';
        end
        for frequency_no = 1:numel(frequencies)
            rows = summary.FrequencyHz == frequencies(frequency_no);
            subset = sortrows(summary(rows, :), 'Rho');
            metric_value_cells{frequency_no} = ...
                subset.(fields{metric_no})(:);
            handles(frequency_no) = semilogx(axis_handle, subset.Rho, ...
                subset.(fields{metric_no}), '-', 'Color', ...
                colors(frequency_no, :), 'LineWidth', 1.65, ...
                'Marker', markers{frequency_no}, 'MarkerSize', 5.2, ...
                'MarkerFaceColor', 'w', 'MarkerEdgeColor', ...
                colors(frequency_no, :));
        end
        metric_values = vertcat(metric_value_cells{:});
        reference_line = xline(axis_handle, 10, '--', '\rho=10', ...
            'Color', [0.28, 0.28, 0.28], 'LineWidth', 0.9, ...
            'LabelOrientation', 'horizontal', ...
            'LabelVerticalAlignment', 'middle', ...
            'LabelHorizontalAlignment', 'left', ...
            'FontName', 'Times New Roman', 'FontSize', 9, ...
            'FontWeight', 'bold', ...
            'HandleVisibility', 'off'); %#ok<NASGU>
        if metric_no == 2
            % Use a separate text object so that the annotation can sit
            % slightly above the NSRE curves without touching the frame.
            reference_line.Label = '';
        end
        xlabel(axis_handle, 'Weighting parameter \rho', ...
            'FontName', 'Times New Roman', 'FontSize', 10.5, ...
            'FontWeight', 'bold');
        ylabel(axis_handle, labels{metric_no}, ...
            'FontName', 'Times New Roman', 'FontSize', 10.5, ...
            'FontWeight', 'bold');
        title(axis_handle, titles{metric_no}, ...
            'FontName', 'Times New Roman', 'FontSize', 11, ...
            'FontWeight', 'bold');
        if isscalar(rho_values)
            x_limits = rho_values(1) .* [0.1, 10];
            x_ticks = rho_values(1);
        else
            x_limits = [rho_values(1), rho_values(end)];
            x_ticks = 10.^(ceil(log10(x_limits(1))): ...
                floor(log10(x_limits(2))));
        end
        set(axis_handle, 'FontName', 'Times New Roman', ...
            'FontSize', 9.5, 'FontWeight', 'normal', 'LineWidth', 1.0, ...
            'TickDir', 'in', 'Layer', 'top', ...
            'XScale', 'log', 'XLim', x_limits, ...
            'XTick', x_ticks, 'XMinorTick', 'on', ...
            'YMinorTick', 'on', 'XMinorGrid', 'on', ...
            'YMinorGrid', 'on', 'GridColor', [0.35, 0.35, 0.35], ...
            'MinorGridColor', [0.45, 0.45, 0.45], ...
            'GridAlpha', 0.25, 'MinorGridAlpha', 0.13, ...
            'GridLineStyle', '--', 'MinorGridLineStyle', ':', ...
            'XColor', [0.12, 0.12, 0.12], ...
            'YColor', [0.12, 0.12, 0.12]);
        % Keep markers clear of the frame and leave extra room for the
        % in-panel legend above the acoustic-contrast curves.
        finite_values = metric_values(isfinite(metric_values));
        if ~isempty(finite_values)
            data_span = max(max(finite_values) - min(finite_values), eps);
            current_limits = ylim(axis_handle);
            upper_fraction = 0.06;
            if metric_no == 1, upper_fraction = 0.15; end
            ylim(axis_handle, [min(current_limits(1), ...
                min(finite_values) - 0.035 * data_span), ...
                max(current_limits(2), ...
                max(finite_values) + upper_fraction * data_span)]);
        end
        if metric_no == 2
            y_limits = ylim(axis_handle);
            text(axis_handle, 10, y_limits(1) + 0.60 * diff(y_limits), ...
                '\rho=10', 'HorizontalAlignment', 'right', ...
                'VerticalAlignment', 'bottom', ...
                'FontName', 'Times New Roman', 'FontSize', 9, ...
                'FontWeight', 'bold', 'Color', [0.28, 0.28, 0.28], ...
                'Tag', 'RhoReferenceLabel');
        end
        if metric_no == 1
            legend_handle = legend(axis_handle, handles, ...
                compose('%g Hz', frequencies), ...
                'Location', 'north', 'NumColumns', 3, ...
                'FontName', 'Times New Roman', 'FontSize', 8.5, ...
                'FontWeight', 'normal', 'Box', 'on', ...
                'Color', 'w', 'EdgeColor', [0.25, 0.25, 0.25]);
            legend_handle.ItemTokenSize = [17, 10];
        end
    end
    base = fullfile(output_dir, basename);
    paths = struct('png', [base '.png'], 'pdf', [base '.pdf'], ...
        'fig', [base '.fig']);
    exportgraphics(figure_handle, paths.png, 'Resolution', 300);
    exportgraphics(figure_handle, paths.pdf, 'ContentType', 'vector');
    savefig(figure_handle, paths.fig);
    close(figure_handle);
end

function tag = local_number_tag(value)
    tag = strrep(sprintf('%.9g', value), '.', 'p');
    tag = strrep(tag, '-', 'm');
    tag = strrep(tag, '+', 'p');
end
